import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  mgbtmp1: {
    marginLeft: 340,
    marginTop: 25,
    backgroundColor: '#ECECF5',
    width: 30,
    height: 30,
    borderRadius: 10,
  },
  ticonmenup: {
    width: 20,
    height: 20,
    alignSelf: 'center',
    marginTop: 4,
  },
  container1: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
  },
  textmispedidos: {
    fontSize: 24,
    fontWeight: '700',
    color: '#49A83F',
    padding: 20,
  },
  box1: {
    borderWidth: 5,
    borderColor: '#F7F7F9',
    height: 90,
    width: 330,
    borderBottomLeftRadius: 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    backgroundColor: '#FFFFFF',
    marginBottom: 13,
    left: 30,
  },
  imgped: {
    width: 70,
    height: 70,
    left: 10,
    top: 10,
  },
  texfechaped: {
    fontSize: 13,
    fontWeight: 'bold',
    marginLeft: 90,
    marginTop: -60,
  },
  textcantprod: {
    fontSize: 10,
    fontWeight: '500',
    marginLeft: 100,
    color: '#C8CFDA',
  },

  ticonmenup1: {
    width: 20,
    height: 20,
    marginLeft: 145,
    marginTop: -10,
  },
  ticonmenup12: {
    width: 40,
    height: 40,
    right: 0,
    left: '80%',
  },
  ticonmenup2: {
    width: 20,
    height: 20,
  },
  box2: {
    borderWidth: 1,
    borderColor: '#FFFFFF',
    height: 75,
    width: 330,
    alignSelf: 'center',
    borderBottomLeftRadius: 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    backgroundColor: '#FFFFFF',
    marginBottom: 13,
  },
  tamañoicono: {
    width: 25,
    height: 25,
  },
  box3: {
    padding: 10,
    flexDirection: 'row',
  },
  textofecha: {
    fontSize: 12,
    color: '#ACB7C9',
    fontWeight: 'bold',
  },
  textohora: {
    fontSize: 20,
    color: '#53535F',
    fontWeight: 'bold',
    marginTop: -22,
  },
  box4: {
    borderWidth: 1,
    borderColor: '#FFFFFF',
    height: 100,
    width: 330,
    alignSelf: 'center',
    borderBottomLeftRadius: 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    backgroundColor: '#FFFFFF',
    marginBottom: 13,
  },
  textoproductos: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#60606C',
  },
  textoproductos1: {
    fontSize: 12,
    fontWeight: 'bold',
    marginLeft: 20,
    color: '#B8C1D1',
  },
  fotoprod: {
    height: 50,
    width: 50,
    marginRight: 10,
    marginTop: -10,
  },
  box5: {
    borderWidth: 1,
    borderColor: '#FFFFFF',
    height: 90,
    width: 330,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    backgroundColor: '#FFFFFF',
    marginTop: 13,
    alignSelf: 'center',
  },
  textoentrega: {
    fontSize: 12,
    color: '#ACB7C9',
    fontWeight: 'bold',
    padding: 10,
  },
  pindireccion: {
    height: 25,
    width: 25,
    padding: 10,
    marginLeft: 10,
  },
  textodireccion: {
    fontSize: 14,
    fontWeight: 'bold',
    alignContent: 'center',
    color: '#686873',
  },
  box6: {
    flexDirection: 'row',
  },
  box7: {
    height: 130,
    width: 330,
    backgroundColor: '#FFFFFF',
    marginTop: 10,
    borderTopWidth: 1.2,
    borderColor: '#F0F0F0',
    alignSelf: 'center',
  },

  txtformpago: {
    fontWeight: 'bold',
    fontSize: 14,
    padding: 10,
    color: '#666672',
  },
  txtformpago1: {
    fontWeight: 'bold',
    fontSize: 14,
    padding: 1,
    marginLeft: 20,
    color: '#666672',
  },
  box8: {
    borderWidth: 0.1,
    height: 50,
    width: 330,
    backgroundColor: '#FFFFFF',
    marginTop: 0,
    borderTopWidth: 0.5,
    borderColor: '#F0F0F0',
    alignSelf: 'center',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    flexDirection: 'row',
  },
  txtotal: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#666672',
    padding: 13,
  },
  txtprecio: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#666672',
    padding: 13,
    marginLeft: 180,
  },
  fotorepartidor: {
    height: 45,
    width: 45,
    marginTop: 10,
  },
  nombrerepartidor: {
    fontWeight: 'bold',
    fontSize: 14,
    marginTop: 17,
    marginLeft: 5,
    color: '#666671',
  },

  repartidor: {
    marginTop: 30,
    fontSize: 10,
    marginRight: 300,
  },
  box9: {
    height: 50,
    width: 330,
    flexDirection: 'row',
  },
  box10: {
    height: 50,
    width: 330,
    flexDirection: 'column',
    backgroundColor: 'blue',
  },
  tipodeli: {
    backgroundColor: '#4CB86A',
    width: 35,
    height: 35,
    borderRadius: 10,
    marginLeft: 240,
    marginTop: -80,
  },
  formaefectivo: {
    backgroundColor: '#4CB86A',
    width: 35,
    height: 35,
    borderRadius: 10,
    marginLeft: 284,
    marginTop: -80,
  },
  estrella: {
    width: 15,
    height: 15,
  },
});

export default styles;
