export const GUARDAR_PRODUCTOS = 'GUARDAR_PRODUCTOS';
export const EDITAR_PRODUCTO = 'EDITAR_PRODUCTO';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';

export const SUMAR_CARRITO = 'SUMAR_CARRITO';
export const RESTAR_CARRITO = 'RESTAR_CARRITO';

export const ACTUALIZAR_ITEMS = 'ACTUALIZA_ITEMS';
export const ACTUALIZAR_CARRITO = 'ACTUALIZAR_CARRITO';
