import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  rowItems: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 5,
    marginBottom: 10,
    width: '50%',
  },
  box4: {
    width: '95%',
    margin: 5,
    marginTop: 0,
    height: 233,
    backgroundColor: '#FFF',
    borderColor: '#F1F1F1',
    borderRadius: 10,
    position: 'relative',
    shadowOffset: {width: 10, height: 10},
    shadowColor: 'black',
    shadowOpacity: 10.0,
    elevation: 4,
  },
  ticonnot3: {
    width: 23,
    height: 23,
    position: 'absolute',
    right: 5,
    borderRadius: 10,
    top: 5,
  },
  ticonnot2: {
    width: '80%',
    height: 100,
    marginLeft: 15,
    marginTop: 24,
    borderRadius: 10,
  },
  NProtxt: {
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 20,
    marginVertical: 3,
  },
  SNPtxt: {
    fontSize: 14,
    marginLeft: 20,
    color: '#B7B7B7',
  },

  Pretxt: {
    marginLeft: 20,
    color: '#2EE107',
    fontSize: 18,
  },
  rowbtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    bottom: 0,
    right: 0,
    position: 'absolute',
    direction: 'ltr',
  },
  btnmas1: {
    backgroundColor: '#FD3A3A',
    width: 40,
    marginRight: 0,
    borderTopLeftRadius: 10,
    bottom: 0,
    left: 8,
    padding: 0,
  },
  btnmas: {
    backgroundColor: '#49A83F',
    width: 40,
    height: 40,
    borderBottomRightRadius: 10,
    borderTopLeftRadius: 10,
    zIndex: 1,
  },
  txtbtn: {
    fontSize: 20,
    color: '#FFF',
    textAlign: 'center',
    zIndex: 3,
    top: 5,
  },
  txtbtn2: {
    fontSize: 20,
    height: 40,
    top: 5,
    color: '#FFF',
    fontWeight: 'bold',
    textAlign: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    display: 'flex',
  },
});

export default styles;
