import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  ticonmenup: {
    width: 30,
    height: 30,
  },
  ticonmenup32: {
    width: 20,
    height: 20,
  },
  mgbtmp: {
    width: 20,
    height: 20,
    marginTop: 25,
    marginLeft: 15,
  },
  mgbtmp1: {
    marginRight: 5,
    backgroundColor: '#B9E9F9',
    width: 30,
    height: 30,
    borderRadius: 10,
  },
  mgbtmp2: {
    marginTop: 0,
    marginLeft: 340,
    backgroundColor: '#ECECF5',
    width: 30,
    height: 30,
    borderRadius: 10,
  },
  mgbtmp3: {
    backgroundColor: '#B9E9F9',
    width: 30,
    height: 30,
    borderRadius: 10,
  },
  ticonnot: {
    width: 23,
    height: 23,
    alignSelf: 'center',
    top: 3,
  },
  tamiconbus: {
    width: 25,
    height: 25,
    marginTop: 10,
    marginLeft: 10,
    marginRight: 10,
  },
  borde: {
    flex: 1,
  },
  passwordContainer: {
    flexDirection: 'row',
    borderRadius: 10,
    marginLeft: 25,
    backgroundColor: '#ECECF5',
    height: 48,
    width: 280,
    marginTop: -45,
  },
  box4: {
    width: 160,
    margin: 12,
    height: 160,
    backgroundColor: '#FFF',
    borderWidth: 2,
    borderColor: '#ECECF5',
    borderRadius: 10,
  },
  box3: {
    marginTop: -12,
    width: 160,
    margin: 12,
    height: 160,
    backgroundColor: '#FFF',
    borderWidth: 2,
    borderColor: '#ECECF5',
    borderRadius: 10,
  },
  box5: {
    width: 80,
    margin: 4,
    height: 80,
    backgroundColor: 'transparent',
    borderWidth: 4,
    borderColor: '#ECECF5',
    borderRadius: 10,
  },
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#F0F0F0',
  },
  container2: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 5,
  },
  ticonnot1: {
    width: 70,
    height: 70,
    marginLeft: 5,
    marginTop: 5,
  },
  txttppro: {
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '600',
    color: '#C4C4C8',
  },
  txtprofile: {
    textAlign: 'left',
    fontSize: 26,
    fontWeight: '600',
    color: '#AAB5C7',
    marginLeft: 30,
    marginTop: -10,
    width: 60,
  },
  imgprofile: {
    alignSelf: 'center',
    width: 150,
    height: 150,
    top: -45,
    elevation: 8,
  },
  botoncamara: {
    width: 150,
    height: 150,
  },
  fotoeditar: {
    marginLeft: 215,
    width: 45,
    height: 45,
    top: -85,
    elevation: 10,
  },
  txtnombreprofile: {
    fontSize: 18,
    textAlign: 'center',
    fontWeight: '500',
    color: '#66656B',
    marginBottom: 1,
  },
  txtdireccion: {
    fontSize: 12,
    textAlign: 'center',
    marginBottom: 40,
  },
  viewprofilepedidos: {
    top: -70,
    backgroundColor: 'white',
    elevation: 5,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    width: 350,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: 'red',
    height: 90,
  },
  box: {
    width: 150,
    height: 90,
    backgroundColor: '#FFF',
    borderTopLeftRadius: 30,
    borderBottomLeftRadius: 30,
    borderColor: '#B1B1B1',
    borderRightWidth: 1,
  },
  box7: {
    width: 150,
    height: 90,
    backgroundColor: '#FFF',
    borderTopRightRadius: 30,
    borderBottomRightRadius: 30,
    borderColor: 'blue',
  },
  container1: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
  },
  btnubno: {
    position: 'absolute',

    right: 20,
    top: 20,
    display: 'flex',
    flexDirection: 'row',
  },
  fotopedidosperfil: {
    marginLeft: 3,
    marginTop: 20,
    width: 40,
    height: 40,
  },
  fotofavperfil: {
    left: 13,
    marginTop: 21,
    width: 40,
    height: 40,
  },
  textpedidosperfil: {
    textAlign: 'center',
    marginTop: -37,
    marginLeft: 20,
    color: '#B5BECE',
    fontWeight: 'bold',
  },
  textpedidosperfil1: {
    textAlign: 'center',
    marginTop: -37,
    marginLeft: 35,
    color: '#B5BECE',
    fontWeight: 'bold',
  },
  box10: {
    borderBottomWidth: 1,
    width: 320,
    alignSelf: 'center',
    borderColor: '#EDF0F4',
    flexDirection: 'row',
    backgroundColor: 'transparent',
    height: 36,
  },

  iconoperfil: {
    height: 27,
    width: 27,
    marginBottom: 2,
    marginTop: 2,
  },
  iconoperfil1: {
    height: 22,
    width: 22,
    marginTop: 6,
    left: 4,
  },
  numeroperfil: {
    color: '#23B1F1',
    fontWeight: 'bold',
    fontSize: 24,
    marginLeft: 57,
  },
  numeroperfil1: {
    color: '#23B1F1',
    fontWeight: 'bold',
    fontSize: 24,
    marginLeft: 62,
  },
  box6: {
    backgroundColor: '#FFFFFF',
  },

  box13: {
    borderColor: '#EEEEEE',
    borderWidth: 1,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    width: 350,
    alignSelf: 'center',
    bottom: 65,
  },

  box11: {
    borderColor: '#EEEEEE',
    borderWidth: 1,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderBottomRightRadius: 30,
    borderBottomLeftRadius: 30,
    width: 350,
    alignSelf: 'center',
    bottom: 50,
  },
  box33: {
    borderColor: '#EEEEEE',
    borderWidth: 1,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderBottomRightRadius: 30,
    borderBottomLeftRadius: 30,
    width: 350,
    alignSelf: 'center',
    bottom: 40,
  },

  mgbtmp5: {
    marginTop: 1,
    marginLeft: 15,
    width: 30,
  },

  botoneditar: {
    width: 60,
    height: 30,
    marginLeft: 230,
    marginTop: -30,
  },
  botonnoti: {
    width: 30,
    height: 30,
    marginLeft: 280,
    marginTop: 30,
  },

  textoeditperfil: {},
  wea: {
    marginLeft: 100,
  },
  btnSeguir: {
    marginTop: 10,
    backgroundColor: '#1580F7',
    height: 45,
    width: 300,
    alignSelf: 'center',
    borderBottomEndRadius: 10,
    borderBottomLeftRadius: 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },

  textbutton: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
    alignSelf: 'center',
    marginTop: 8,
  },

  textomicarro: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#ABB3C5',
    marginLeft: 28,
    marginTop: 20,
  },

  box1: {
    width: '100%',

    marginBottom: 13,
  },
  contenedorproducto: {
    height: 100,
    alignSelf: 'center',
    borderRadius: 15,
    width: '90%',
    backgroundColor: '#FEFEFE',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
  },

  fotoprod: {
    position: 'absolute',
    height: 60,
    width: 60,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 10,
    top: 20,
    left: 10,
    borderBottomRightRadius: 10,
  },

  nombreprod: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#AFAFB0',
    left: -20,
  },

  nombretipoprod: {
    fontSize: 10,
    left: -25,
    color: '#CBCCD1',
  },
  txtprecio: {
    color: '#26B3F1',
    left: -40,
  },

  botonespedidos: {
    position: 'absolute',
    right: 30,
    backgroundColor: '#FD3A3A',
    height: 45,
    width: 55,
    bottom: 0,
    borderTopLeftRadius: 15,
  },
  botonespedidos1: {
    position: 'absolute',
    backgroundColor: '#49A83F',
    height: 45,
    width: 45,
    right: 0,
    bottom: 0,

    borderBottomRightRadius: 10,
    borderTopLeftRadius: 20,
  },
  txtbotones: {
    color: '#CFE8D4',
    fontSize: 19,
    alignSelf: 'center',
    marginTop: 5,
  },
  favoron: {
    position: 'absolute',
    height: 15,
    width: 15,
    right: 10,
    top: 5,
  },

  txtpodrias: {
    fontWeight: 'bold',
    color: '#B5B9C0',
    marginLeft: 10,
  },

  box2: {
    marginTop: 20,
    borderColor: '#FFFFFF',
    borderBottomLeftRadius: 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    backgroundColor: '#FFFFFF',
    width: 350,
    height: 150,
    flexDirection: 'row',
    marginLeft: 20,

    marginBottom: 2,
  },

  favoronrec: {
    height: 25,
    width: 25,
    marginLeft: 130,
    marginTop: -85,
  },

  nombreprodrec: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#8C8B90',
    marginTop: 10,
    marginLeft: 20,
  },
  nombretipoprodrec: {
    fontSize: 12,
    marginLeft: 20,
    color: '#CBCCD1',
    marginTop: 1,
  },
  txtpreciorec: {
    color: '#81A897',
    marginLeft: 20,
  },

  fotoprodrec: {
    height: 65,
    width: 65,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    alignSelf: 'center',
    marginTop: 2,
  },
  txtbotonesrec: {
    color: '#CFE8D4',
    fontSize: 24,
    alignSelf: 'center',
    marginTop: 5,
  },
  botonespedidosrec: {
    marginLeft: 132,
    backgroundColor: '#4FB667',
    height: 50,
    width: 45,
    marginTop: -15,
    borderTopLeftRadius: 15,
    borderBottomRightRadius: 20,
  },
  cajarecomendado: {
    flexDirection: 'row',
  },
  pagarContainer: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
  },
  cajairapagar: {
    flexDirection: 'row',
    backgroundColor: '#49A83F',
    height: 60,
    width: '90%',
    borderRadius: 15,
    marginTop: 15,
    marginLeft: 20,
  },
  txtcantidad: {
    fontSize: 24,
    alignSelf: 'center',
    color: '#FFF',
    fontWeight: 'bold',
  },
  txtirpagar: {
    fontSize: 20,
    color: '#E6FFFF',
    alignSelf: 'center',
    fontWeight: 'bold',
    marginLeft: 80,
  },
  txtpagar: {
    fontSize: 18,
    color: '#E6FFFF',
    alignSelf: 'center',
    position: 'absolute',
    right: 10,
  },
  boxcantidad: {
    backgroundColor: '#7BC174',
    marginLeft: 10,
    height: 35,
    width: 35,
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    marginTop: 5,
    alignSelf: 'center',
  },
  vaciarcarro: {
    color: '#1680F8',
    fontSize: 18,
    alignSelf: 'center',
    marginTop: 10,
  },
  boxscroll: {
    width: 127,
    height: 140,
    marginLeft: 10,
    elevation: 1,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 9,
  },
  txtperfil: {
    color: '#1DAFF1',
    fontWeight: 'bold',
    fontSize: 28,
    left: 30,
    top: -40,
  },
  logo: {
    height: 50,
    width: 150,
    alignSelf: 'center',
    bottom: 38,
    right: 10,
  },
  txtnombreprofile1: {
    fontSize: 16,
    textAlign: 'center',
    fontWeight: 'bold',
    color: '#66656B',
    bottom: 80,
  },
  txtdireccion1: {
    fontSize: 12,
    textAlign: 'center',
    bottom: 80,
    color: '#B1B1B1',
    fontWeight: 'bold',
  },
  viewinfousuario: {
    width: 330,
    height: 210,

    alignSelf: 'center',
    borderRadius: 10,
    top: -45,
  },
  txtinfousuario: {
    fontSize: 14,
    color: '#B1B1B1',
    fontWeight: 'bold',
    left: 17,
    top: 6,
  },
});
export default styles;
