import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  ticonmenup: {
    width: 30,
    height: 30,
  },
  mgbtmp: {
    marginTop: 25,
    marginLeft: 15,
    width: 40,
  },
  mgbtmp2: {
    backgroundColor: '#B9E9F9',
    width: 30,
    height: 30,
    borderRadius: 10,
  },
  contNoti: {
    marginTop: 20,
    width: '100%',
    height: 48,
    marginBottom: 8,
    display: 'flex',
    flexDirection: 'row-reverse',
    position: 'relative',
  },
  mgbtmp3: {
    position: 'absolute',
    width: '13%',
    height: 48,
    backgroundColor: '#49A83F',
    left: '6%',
    borderRadius: 10,
  },
  ticonnot: {
    width: 36,
    height: 36,
    alignSelf: 'center',
    marginTop: 4,
  },
  tamiconbus: {
    width: 25,
    height: 25,
    marginTop: 10,
    marginLeft: 10,
    marginRight: 10,
  },
  borde: {
    flex: 1,
  },
  passwordContainer: {
    flexDirection: 'row',
    borderRadius: 10,
    marginLeft: 15,
    backgroundColor: '#E8F7FC',
    height: 48,
    width: 280,
    marginTop: -55,
  },
  box5: {
    maxWidth: 80,
    margin: 4,
    maxHeight: 80,
    backgroundColor: '#FFFFFF',
    elevation: 2.5,
    shadowOpacity: 87.8,
    borderColor: '#ECECF5',
    borderRadius: 15,
    marginTop: 2,
    marginBottom: 10,
  },
  boxactive: {
    width: 80,
    margin: 4,
    height: 80,
    backgroundColor: '#49A83F',
    elevation: 2.5,
    shadowOpacity: 87.8,
    borderColor: '#ECECF5',
    borderRadius: 15,
    marginTop: 2,
    marginBottom: 10,
  },
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    position: 'relative',
  },
  row: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 5,
    marginBottom: 10,
    width: '100%',
  },
  row2: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    width: '100%',
    borderRadius: 2,
  },
  ticonnot1: {
    width: 70,
    height: 70,
    marginLeft: 5,
    marginTop: 5,
  },
  txttppro: {
    textAlign: 'center',
    top: 15,
    fontSize: 12,
    fontWeight: '600',
    color: '#3CBAF3',
  },
  achique: {
    width: 40,
    marginTop: -45,
    marginLeft: 130,
    marginBottom: -20,
  },
  logoHome: {
    height: 70,
    width: 110,
  },
  iconosarriba: {
    width: '80%',
    height: 20,
    marginTop: 5,
    alignSelf: 'center',
  },
  contIcons: {
    position: 'absolute',
    display: 'flex',
    flexDirection: 'row',
    right: 5,
    top: 25,
  },
  mgbtmp10: {
    marginRight: 5,
    backgroundColor: '#B9E9F9',
    width: 30,
    height: 30,
    borderRadius: 10,
  },
  listview: {
    flex: 1,
    marginHorizontal: 18,
    display: 'flex',
  },
  listnone: {
    display: 'none',
  },
});
export default styles;
