import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  ticonmenup: {
    width: 30,
    height: 30,
  },
  mgbtmp: {
    marginTop: 25,
    marginLeft: 15,
    width: 40,
  },
  btnubno: {
    position: 'absolute',
    right: 20,
    top: 20,
    display: 'flex',
    flexDirection: 'row',
  },
  mgbtmp2: {
    backgroundColor: '#B9E9F9',
    width: 30,
    height: 30,
    borderRadius: 10,
  },
  passwordContainer1: {
    flexDirection: 'row', 
    marginLeft: 25,
    height: 48,
    width: 280,
    marginTop: 25,
  },
  txtpromo: {
    fontSize: 30,
    fontWeight: '700',
    color: '#49A83F',
  },
  boxpromo: {
    width: 340,
    margin: 5,
    marginTop: 10,
    height: 160,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#ECECF5',
    borderRadius: 10,
    elevation: 2,
  },
  image: {
    width: 340,
    height: 160,
    borderRadius: 10,
  },
  box5: {
    maxWidth: 80,
    margin: 4,
    maxHeight: 80,
    backgroundColor: '#FFFFFF',
    elevation: 2.5,
    shadowOpacity: 87.8,
    borderColor: '#ECECF5',
    borderRadius: 15,
    marginTop: 2,
    marginBottom: 10,
  },
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    position: 'relative',
  },
  row: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 5,
    marginBottom: 10,
    width: '100%',
  },
  ticonnot1: {
    width: 70,
    height: 70,
    marginLeft: 5,
    marginTop: 5,
  },
  txttppro: {
    textAlign: 'center',
    top: 15,
    fontSize: 12,
    fontWeight: '600',
    color: '#3CBAF3',
  },
  row1: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 5,
    marginBottom: 10,
  },
  iconosarriba: {
    width: '80%',
    height: 20,
    marginTop: 5,
    alignSelf: 'center',
  },
  mgbtmp10: {
    marginRight: 5,
    backgroundColor: '#B9E9F9',
    width: 30,
    height: 30,
    borderRadius: 10,
  },
});
export default styles;
